name: aniview
description: "AniView: watch and track anime with AniList or MyAnimeList."
publish_to: 'none'
version: 2.1.2+13

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.2.0-beta.3
  http: ^1.6.0
  http2: ^2.3.1
  path_provider: ^2.1.6
  pointycastle: ^4.0.0
  screen_brightness: ^2.1.11
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/aniview_icon.png
